version: "3.0"

volumes:
  tut12-mongo-keys:
  tut12-mongo-data-0:
  tut12-mongo-data-1:
  tut12-mongo-data-2:
  tut12-mongo-data-3:

networks:
  tut12-replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24

services:

  tut12-mongo-keys:
    image: depop/openssl-bats
    volumes:
      - tut12-mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Primary
  tut12-mongo-primary:
    image: mongo:latest
    volumes:
      - tut12-mongo-keys:/opt/keyfile
      - tut12-mongo-data-0:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet tut12-replica-set'
    depends_on:
        - tut12-mongo-keys
    networks:
      tut12-replica-set:
  
  # Worker 1
  tut12-mongo-worker-1:
    image: mongo:latest
    volumes:
      - tut12-mongo-keys:/opt/keyfile
      - tut12-mongo-data-1:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet tut12-replica-set'
    depends_on:
        - tut12-mongo-keys
    networks:
      tut12-replica-set:
  
  # Worker 2
  tut12-mongo-worker-2:
    image: mongo:latest
    volumes:
      - tut12-mongo-keys:/opt/keyfile
      - tut12-mongo-data-2:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet tut12-replica-set'
    depends_on:
        - tut12-mongo-keys
    networks:
      tut12-replica-set:
  
  # Worker 3
  tut12-mongo-worker-3:
    image: mongo:latest
    volumes:
      - tut12-mongo-keys:/opt/keyfile
      - tut12-mongo-data-3:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27020:27017
    command: 'mongod --smallfiles --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet tut12-replica-set'
    depends_on:
        - tut12-mongo-keys
    networks:
      tut12-replica-set: